### ISSUE TITLE
Notes integration

### ISSUE THREAD

**Issue by Polpetta** [Polpetta/MobileProgrammingNotes#2]
**Description**
Integrare le note di @GiacomoManzoli con quelle che ho preso io a suo tempo
**Other issues**
Farlo prima che gli altri facciano tutto il resto o viene casotto

**Comment by mdipirro** [comment]
Nei capitoli 2 e 3 alcune immagini schizzano fuori dai margini e si vedono a metà

**Comment by Polpetta** [comment]
Sisi! Ci sto ancora lavorando su! Per il momento le avevo buttate dentro al repository così @mzanella e @EmanueleC potevano cominciare a lavorare sul capitolo 2. Appena finiscono lo metto in ordine, mentre mi manca il cap3 da aggiustare.
