### ISSUE TITLE
Lez 3

### ISSUE THREAD

**Issue by Polpetta** [Polpetta/MobileProgrammingNotes#7]
**Description**
Integrare [le seguenti slide](http://www.math.unipd.it/~abujari/mprogramming/lecSlides/Lec-S3.pdf) negli appunti. Suddividetevi da solito gli argomenti che riassumerete.
**Other issues**

**Comment by mzanella** [comment]
Nella parte iniziale della lezione riguardante la localizzazione (dovrebbe essere appunto questa) le subsections partono dallo 0 invece che dall'1

![image](https://user-images.githubusercontent.com/12596262/27428032-1c20475a-5741-11e7-8a19-d4348c66af3a.png)
