### ISSUE TITLE
Android Examples

### ISSUE THREAD

**Issue by Polpetta** [Polpetta/MobileProgrammingNotes#8]
**Description**
Scrivere e dare una spiegazione pratica dei vari esempi che abbiamo visto in tutti i laboratori affrontati. La spiegazione dev'essere del tipo "perche' si fa cosi'"
**Other issues**

**Comment by mdipirro** [comment]
@EduBic manca lab 4

**Comment by Polpetta** [comment]
@mdipirro @EduBic chiudo?

**Comment by EduBic** [comment]
No, manca lab4. Vedo se oggi riesco a fare almeno le prime 3 app.
