### ISSUE TITLE
Gaggi's slides

### ISSUE THREAD

**Issue by Polpetta** [Polpetta/MobileProgrammingNotes#9]
**Description**
Integrare [questa](http://www.math.unipd.it/~abujari/mprogramming/lecSlides/Lec-S4P1.pdf) e [questa](http://www.math.unipd.it/~abujari/mprogramming/lecSlides/Lec-S4P2.pdf) slide negli appunti.
**Other issues**

**Comment by mzanella** [comment]
Non fanno parte dell'esame
